spring:
  application:
    name: book-service
  cloud:
    openfeign:
      enabled: true
server:
  port: 8100

##eureka:
##  client:
##    service-url:
##      defaultZone: http://localhost:8761/eureka/
